name:                TPLogo
version:             0.1.0.0
github:              "swirzt/ALP/TPLogo"
license:             BSD3
author:              "Santiago Wirzt"
maintainer:          "swirzt@gmail.com"
copyright:           "2021 Santiago Wirzt"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TPLogo#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- array
- containers
- random >= 1.2.1
- mtl
- haskeline
- exceptions

library:
  source-dirs: src

executables:
  TPLogo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TPLogo

tests:
  TPLogo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TPLogo
